// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Surprise.Library;
using System;

namespace Surprise.DataBase.Migrations
{
    [DbContext(typeof(Model))]
    [Migration("20180504120226_New_Migration")]
    partial class New_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("Surprise.Library.Surprise_MessageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Date");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Surprise_MessageDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
